resources:
- name: resource-ravi-1
  type: git
  source:
   uri: https://github.com/rravind/ravi-concourse-trg-repo.git
   branch: master
 
jobs:
- name: job-ravi-1
  plan:
    - get: resource-ravi-1
      trigger: true
    - task: task-list-ravi-1
      file: resource-ravi-1/tasks/task-list-ravi.yml